### ISSUE TITLE
The scoretable isn't synchronizing online

### ISSUE THREAD

**Issue by interduo** [mklopotek/gamesnake#2]
I and my friends are playing gamesnake for some time and need to compete with each other. We do all what we can with the snake, but the scores aren't saved online.

We could get Your game online on our server just say it loud.

**Comment by mklopotek** [comment]
Dear Friend! :)
Thank you for your comments. I would be grateful it if you could put my game on your server.

**Comment by interduo** [comment]
I feel like as buyer on aliexpress now.

Few years ago I gave You an account on our server. Feel free to use it. Just upload a code to FTP server and access it by your web alias.
If You would like my support please let me know.

**Comment by interduo** [comment]
I proppose to show scoretable not only after end of the game but also when playing game.
(So we could check the results without playing game).

**Comment by interduo** [comment]
Done.
